<?php

$api = "https://download.moodle.org/api/1.3/pluglist.php";
$satisfile = __DIR__ . '/satis.json';

$pluginlistjson = file_get_contents($api);

if (!$pluginlist = json_decode($pluginlistjson)) {
    die("Unable to read plugin list");
}

$satisjson = [];
$satisjson['name'] = "michaelmeneses/moodle-plugin-repo";
$satisjson['homepage'] = "https://satis.middag.com.br";
$satisjson['repositories'] = [];

$ignore = [
    'https://:@bucket.org/schoolsict/block_zilink.git',
    'https://bitbucket.org/covuni/bcu-course-checks-block',
    'https://bitbucket.org/covuni/moodle-mod_bootstrapelements',
    'https://bitbucket.org/schoolsict/auth_zilink_guardian.git',
    'https://bitbucket.org/schoolsict/enrol_zilink.git',
    'https://bitbucket.org/schoolsict/enrol_zilink_cohort.git',
    'https://bitbucket.org/schoolsict/local_zilink.git',
    'https://bitbucket.org/sebsoft/moodle-auth_antihammer',
    'https://bitbucket.org/sebsoft/moodle-block_coupon',
    'https://bitbucket.org/sebsoft/moodle-block_selectrss',
    'https://bitbucket.org/sebsoft/moodle-enrol_classicpay',
    'https://bitbucket.org/sebsoft/moodle-tool_userrestore/',
    'https://bitbucket.org/sebsoft/moodle-tool_usersuspension',
    'https://bitbucket.org/uonmoodle/moodle-local_fullscreen.git',
    'https://bitbucket.org/uonmoodle/moodle-mod_allocationform.git',
    'https://bitbucket.org/uonmoodle/moodle-mod_tutorialbooking/',
    'https://bitbucket.org/uonmoodle/moodle-repository_xpert_flickr_public/',
    'https://bitbucket.org/uonmoodle/moodle-repository_xpert_upload',
    'https://bitbucket.org/uonmoodle/moodle-repository_xpert_url',
    'https://git.framasoft.org/ebugnet/moodle-block_dyslexic',
    'https://github.com/3-bits/moodle-theme_joomdlebs',
    'https://github.com/3ilogiclms/moodle-block_course_finder',
    'https://github.com/3ilogiclms/moodle-block_course_status_tracker',
    'https://github.com/3ilogiclms/moodle-block_learning_plan',
    'https://github.com/3ilogiclms/moodle-block_profile_field_identifier',
    'https://github.com/3ilogiclms/moodle-block_sms',
    'https://github.com/3ilogiclms/moodle-theme_contemporary',
    'https://github.com/3ilogiclms/moodle-theme_dynamic',
    'https://github.com/3ilogiclms/moodle-theme_sharp',
    'https://github.com/CLAMP-IT/moodle-blocks_filtered_course_list',
    'https://github.com/CTANZ/moodle-theme_decaf',
    'https://github.com/Celumproject/moodle-mod_domoscio',
    'https://github.com/CinecaElearning/moodle-mod_attendanceregister',
    'https://github.com/DigiDago/moodle-block_admin_presets',
    'https://github.com/EEXCESS/moodle-block_eexcess',
    'https://github.com/EizEddin/moodle-block_login_userinfo',
    'https://github.com/EllucianMoodleIntegration/moodle-block_intelligent_learning',
    'https://github.com/FMCorz/moodle-availability_xp',
    'https://github.com/FMCorz/moodle-repository_evernote/tree/plugin',
    'https://github.com/HaakonME/moodle-booktool_exportepub.git',
    'https://github.com/HaakonME/moodle-booktool_importepub.git',
    'https://github.com/Hipjea/moodle-block_studentstracker',
    'https://github.com/KepaUrzelai/moodle-atto_multilang2',
    'https://github.com/Kylegoslin/Course-Request-Manager',
    'https://github.com/Kylegoslin/moodle-block_faces',
    'https://github.com/Kylegoslin/moodle-block_signinsheet',
    'https://github.com/LafColITS/Moodle-auth_casattras',
    'https://github.com/LafColITS/moodle-local_metasync',
    'https://github.com/LafColITS/moodle-local_news_forum',
    'https://github.com/LafColITS/moodle-local_remote_backup_provider',
    'https://github.com/LafColITS/moodle-report_roster',
    'https://github.com/MMDevelopment/moodle-block_credly',
    'https://github.com/MaharaProject/moodle-assignsubmission_mahara',
    'https://github.com/Microsoft/moodle-assignfeedback_onenote',
    'https://github.com/Microsoft/moodle-assignsubmission_onenote',
    'https://github.com/Microsoft/moodle-auth_oidc',
    'https://github.com/Microsoft/moodle-block_microsoft',
    'https://github.com/Microsoft/moodle-block_onenote',
    'https://github.com/Microsoft/moodle-local_microsoftservices',
    'https://github.com/Microsoft/moodle-local_msaccount',
    'https://github.com/Microsoft/moodle-local_o365',
    'https://github.com/Microsoft/moodle-local_office365',
    'https://github.com/Microsoft/moodle-local_onenote',
    'https://github.com/Microsoft/moodle-repository_office365',
    'https://github.com/Microsoft/moodle-repository_onenote',
    'https://github.com/MorrisR2/moodle_local_searchquestions',
    'https://github.com/NMAI-lab/moodle-mod_socialwiki',
    'https://github.com/PeloNZ/moodle-block_yammer',
    'https://github.com/PlagScan/PlagScan_moodle',
    'https://github.com/PlaneteStream/moodle-assignsubmission_estream',
    'https://github.com/PlaneteStream/moodle-atto_planetestream',
    'https://github.com/PlaneteStream/moodle-filter_planetestream',
    'https://github.com/PlaneteStream/moodle-tinymce_planetestream',
    'https://github.com/PoetOS/moodle-filter_oembed',
    'https://github.com/RusticiSoftware/SCORMCloud_MoodleModule',
    'https://github.com/SREd-URV/moodle-auth_ip',
    'https://github.com/SREd-URV/moodle-profilefield_timestamp',
    'https://github.com/SVIeSolutions/moodle-mod_via',
    'https://github.com/SonicFoundry/Mediasite-Content-Module-for-Moodle',
    'https://github.com/UNEDLabs/moodle-block_ejsapp_collab_session',
    'https://github.com/UNEDLabs/moodle-block_ejsapp_file_browser',
    'https://github.com/UNEDLabs/moodle-mod_ejsapp',
    'https://github.com/UNEDLabs/moodle-mod_ejsappbooking',
    'https://github.com/UNEDLabs/moodle-repository_osp',
    'https://github.com/UbiCastTeam/moodle-mod_easycastms.git',
    'https://github.com/UniversityofPortland/moodle-block_custom_course_menu',
    'https://github.com/Unplag/moodle-plagiarism_unplag',
    'https://github.com/abgreeve/moodle-calendartype_japanese',
    'https://github.com/academic-moodle-cooperation/moodle-atto_bsgrid',
    'https://github.com/academic-moodle-cooperation/moodle-blocks_semester_sortierung',
    'https://github.com/academic-moodle-cooperation/moodle-gradereport_gradedist/',
    'https://github.com/academic-moodle-cooperation/moodle-local_checkmarkreport',
    'https://github.com/academic-moodle-cooperation/moodle-mod_checkmark',
    'https://github.com/academic-moodle-cooperation/moodle-mod_grouptool',
    'https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz',
    'https://github.com/academic-moodle-cooperation/moodle-mod_organizer',
    'https://github.com/academic-moodle-cooperation/moodle-mod_publication',
    'https://github.com/actXc/moodle_filter_botr',
    'https://github.com/adrienedunao/mod_richmedia',
    'https://github.com/aduranterres/auth_joomdle',
    'https://github.com/aduranterres/enrol_signup',
    'https://github.com/ak4t0sh/moodle-filter_codepen',
    'https://github.com/ak4t0sh/moodle-format_weeksrev',
    'https://github.com/alexandru-elisei/moodle-tool_downloaddata',
    'https://github.com/amandadoughty/moodle-block_culactivity_stream/tree/master',
    'https://github.com/amandadoughty/moodle-block_culupcoming_events',
    'https://github.com/amandadoughty/moodle-local_culactivity_stream',
    'https://github.com/amandadoughty/moodle-local_culcourse_visibility',
    'https://github.com/amandadoughty/moodle-message_culactivity_stream',
    'https://github.com/andiglombitza/CLOZE_editor_Moodle2.2',
    'https://github.com/andil-elearning/moodle-block_section',
    'https://github.com/andrewhancox/block_databasetags',
    'https://github.com/andrewhancox/datafield_linkedcheckbox',
    'https://github.com/andrewhancox/datafield_tag',
    'https://github.com/andrewnicols/moodle-atto_fontsize',
    'https://github.com/ankitagarwal/advanced_spam_cleaner',
    'https://github.com/ankitagarwal/moodle-block_fbcomments.git',
    'https://github.com/ankitagarwal/moodle-scormreport_trends',
    'https://github.com/annotate-co/moodle-block_annotate',
    'https://github.com/appalachianstate/moodle-enrol_shebang',
    'https://github.com/appalachianstate/moodle-local_userenrols',
    'https://github.com/arael/moodle_notifications_20',
    'https://github.com/arborrow/moodle-block_mrbs',
    'https://github.com/at-tools/moodle-block_massaction',
    'https://github.com/benchen71/moodle-filter_toc',
    'https://github.com/blackboard-open-source/moodle-format_folderview',
    'https://github.com/blackboard-open-source/moodle-local_mr',
    'https://github.com/blackboard-open-source/moodle-mod_collaborate',
    'https://github.com/blackboard-open-source/moodle-mod_hsuforum',
    'https://github.com/blackboard-open-source/moodle-theme_snap',
    'https://github.com/blindsidenetworks/moodle-mod_recordingsbn',
    'https://github.com/bmbrands/moodle-local_welcome',
    'https://github.com/bobopinna/moodle-enrol_autoenrol',
    'https://github.com/bobopinna/moodle-mod_reservation',
    'https://github.com/bostelm/moodle-mod_scheduler',
    'https://github.com/bozoh/moodle-block_simple_certificate',
    'https://github.com/brissone/moodle-qtype_musictheory',
    'https://github.com/catalyst/moodle-auth_basic',
    'https://github.com/catalyst/moodle-auth_enrolkey',
    'https://github.com/catalyst/moodle-auth_saml2',
    'https://github.com/catalyst/moodle-local_datacleaner',
    'https://github.com/catalyst/moodle-local_envbar',
    'https://github.com/catalyst/moodle-local_qrlinks',
    'https://github.com/catalyst/moodle-mod_facetoface/',
    'https://github.com/catalyst/moodle-report_coursesize',
    'https://github.com/catalyst/moodle-tool_heartbeat',
    'https://github.com/cescobedo/moodle-auth_dev.git',
    'https://github.com/cescobedo/moodle-local_navigation.git',
    'https://github.com/cescobedo/moodle-local_upgradedb.git',
    'https://github.com/coderader/moodle-block_userexpire',
    'https://github.com/compilatio/moodle-plagiarism_compilatio/tree/PLUGIN_24_STABLE',
    'https://github.com/ctchanandy/moodle-report_forumgraph/tree/Moodle-3.1',
    'https://github.com/curupira/moodle-mod_registration',
    'https://github.com/damyon/moodle-atto_count.git',
    'https://github.com/damyon/moodle-atto_hr.git',
    'https://github.com/damyon/moodle-editor_webvi.git',
    'https://github.com/damyon/moodle-local_morelockfactories',
    'https://github.com/danmarsden/moodle-plagiarism_urkund',
    'https://github.com/dasistwas/moodle-block_simple_map',
    'https://github.com/dasistwas/moodle-block_simple_nav/',
    'https://github.com/dasistwas/moodle-mod_booking/',
    'https://github.com/dasistwas/moodle-mod_newsletter',
    'https://github.com/dasistwas/moodle-theme_campus/',
    'https://github.com/dasistwas/moodle-theme_squared',
    'https://github.com/daveyboond/moodle-mcq-report-only',
    'https://github.com/davidherney/moodle-format_socialwall',
    'https://github.com/davidscotson/moodle-tool_themetester',
    'https://github.com/davosmith/moodle-assignfeedback_pdf',
    'https://github.com/davosmith/moodle-assignsubmission_pdf',
    'https://github.com/davosmith/moodle-block_checklist',
    'https://github.com/davosmith/moodle-checklist',
    'https://github.com/davosmith/moodle-grade_checklist',
    'https://github.com/davosmith/moodle-navbuttons',
    'https://github.com/davosmith/moodle-objectives',
    'https://github.com/davosmith/moodle-realtimequiz',
    'https://github.com/deraadt/moodle-block_heatmap',
    'https://github.com/deraadt/moodle-block_progress',
    'https://github.com/deraadt/moodle-block_simple_clock.git',
    'https://github.com/deraadt/moodle-block_unanswered_discussions',
    'https://github.com/discendum/obf-moodle',
    'https://github.com/dmelearn/moodle-mod_dmelearn/',
    'https://github.com/donhinkelman/moodle-block_sharing_cart',
    'https://github.com/drachels/moodle-mod_hotquestion',
    'https://github.com/drachels/moodle-mod_mootyper',
    'https://github.com/drachels/moodle-mod_skype',
    'https://github.com/dthies/moodle-atto_fullscreen',
    'https://github.com/dthies/moodle-atto_mathslate',
    'https://github.com/dthies/moodle-atto_preview',
    'https://github.com/dthies/moodle-editor_tinymce-mathslate',
    'https://github.com/dthies/moodle-qbehaviour_adaptiveallnothing',
    'https://github.com/dthies/moodle-qbehaviour_deferredallnothing',
    'https://github.com/dualcube/Drag-and-Drop-Matching',
    'https://github.com/dualcube/moodle-block_my_enrolled_courses',
    'https://github.com/dualcube/moodle-enrol_authorizedotnet',
    'https://github.com/dualcube/moodle-enrol_bitcoin',
    'https://github.com/dualcube/moodle-enrol_stripepayment',
    'https://github.com/dualcube/moodle-theme_crisp',
    'https://github.com/dualcube/moodle-theme_rocket',
    'https://github.com/dualcube/moodle-theme_roshnilite',
    'https://github.com/dualcube/moodle-tinymce_virtualkeyboard',
    'https://github.com/dualcube/moodle-tool_inactive_user_cleanup',
    'https://github.com/eLearning-TUDarmstadt/moodle-report_moodleanalyst',
    'https://github.com/eberhardt/moodle-block_coursefeedback',
    'https://github.com/eberhardt/moodle-block_sitenews',
    'https://github.com/eberhardt/moodle-filter_collapsible',
    'https://github.com/ecampbell/moodle-qformat_htmltable',
    'https://github.com/ecampbell/moodle-qformat_wordtable',
    'https://github.com/ecampbell/moodle-qtype_multichoiceset/tree/master',
    'https://github.com/ed-rom/moodle-auth_uniquelogin',
    'https://github.com/edu-sharing/plugin-moodle',
    'https://github.com/elearningsoftware/moodle-mod_journal',
    'https://github.com/eledia/block_eledia_suspenduser.git',
    'https://github.com/eledia/block_eledia_trainerinfo',
    'https://github.com/eledia/block_eledia_userdelete/tree/v_34/blocks/eledia_userdelete',
    'https://github.com/eledia/eledia_cohortgreeting.git',
    'https://github.com/eledia/eledia_course_archiving/tree/v_25/blocks/eledia_course_archiving',
    'https://github.com/eledia/local_eledia_webservicesuite/tree/v_31',
    'https://github.com/emeneo/moodle-enrol_waitlist',
    'https://github.com/emeneo/moodle-mod_description',
    'https://github.com/emmarichardson/local_autogroup',
    'https://github.com/ensembleVideo/moodle-repository_ensemble/',
    'https://github.com/ethz-let/moodle-qtype_kprime',
    'https://github.com/eugenemodlo/moodle-filter_sagecell',
    'https://github.com/ewallah/moodle-availability_coursecompleted',
    'https://github.com/ewallah/moodle-availability_language',
    'https://github.com/ewallah/moodle-format_masonry',
    'https://github.com/ewallah/moodle-repository_s3bucket',
    'https://github.com/fernandooliveira/moodle-block_mentor',
    'https://github.com/fernandooliveira/moodle-block_sidebar',
    'https://github.com/ffhs/moodle-filter_fontawesome',
    'https://github.com/francpombal/moodle-theme_aigne/',
    'https://github.com/fredcy/moodle-tool_datatables',
    'https://github.com/fschuett/moodle-enrol_openlml',
    'https://github.com/garemoko/moodle-mod_tincanlaunch',
    'https://github.com/gbateson/moodle-mod_reader',
    'https://github.com/gbateson/moodle-mod_taskchain',
    'https://github.com/gbateson/moodle-qtype_ordering',
    'https://github.com/geoffrowland/moodle-editor_atto-chemistry',
    'https://github.com/geogebra/moodle-assignsubmission_geogebra',
    'https://github.com/geogebra/moodle-qtype_geogebra',
    'https://github.com/geogebra/moodle-repository_geogebratube',
    'https://github.com/gerkekok/moodle-plagiarism_ephorus',
    'https://github.com/gjb2048/moodle-block_theme_selector.git',
    'https://github.com/gjb2048/moodle-format_topcoll.git',
    'https://github.com/gjb2048/moodle-theme_shoehorn',
    'https://github.com/gjb2048/moodle-theme_shoelace',
    'https://github.com/grabs/moodle-local_adminer.git',
    'https://github.com/gtn/exagames',
    'https://github.com/gtn/exalib',
    'https://github.com/gtn/exaport',
    'https://github.com/h-honda/moodle-block_login_info',
    'https://github.com/hbattat/a2fa',
    'https://github.com/hrimhari/moodle-auth_emailadmin',
    'https://github.com/humanage/moodle-mod_eduplayer',
    'https://github.com/iamandrew/moodle-block_coursefiles',
    'https://github.com/iamandrew/moodle-block_twitter',
    'https://github.com/iandavidwild/moodle-mod_enhancedchoice',
    'https://github.com/iarenaza/moodle-filter_multilang2',
    'https://github.com/iautomatebr/moodle-block_moodleversion',
    'https://github.com/intelliboard/intelliboard',
    'https://github.com/isuru89/moodle-reminders-for-calendar-events',
    'https://github.com/itamart/moodle-availability_dataformcontent',
    'https://github.com/itamart/moodle-block_dataform_view',
    'https://github.com/itamart/moodle-block_dataformaccessentry',
    'https://github.com/itamart/moodle-block_dataformaccessfield',
    'https://github.com/itamart/moodle-block_dataformaccessview',
    'https://github.com/itamart/moodle-block_dataformnotification',
    'https://github.com/itamart/moodle-block_mhaairs',
    'https://github.com/itamart/moodle-local_loginas',
    'https://github.com/itamart/moodle-mod_dataform',
    'https://github.com/itamart/moodle-mod_dataformembed',
    'https://github.com/jhoopes/moodle-mod_activequiz',
    'https://github.com/jleyva/moodle-availability_mobileapp',
    'https://github.com/jleyva/moodle-block_jmail',
    'https://github.com/jleyva/moodle-local_anonymousposting',
    'https://github.com/jleyva/moodle-local_mobile/',
    'https://github.com/jmpease/moodle-filter_ensemble/',
    'https://github.com/jmvedrine/moodle-mod_qcreate',
    'https://github.com/jmvedrine/moodle-qformat_fronter',
    'https://github.com/jmvedrine/moodle-qformat_giftmedia',
    'https://github.com/jmvedrine/moodle-qtype_algebra',
    'https://github.com/jmvedrine/moodle-qtype_formulas',
    'https://github.com/johndimopoulos/moodle-gradingform_erubric',
    'https://github.com/josePFs/moodle-filter_tabs',
    'https://github.com/juacas/moodle-mod_quest.git',
    'https://github.com/justinhunt/moodle-assign_submission_onlinepoodll',
    'https://github.com/justinhunt/moodle-assignfeedback_poodll.git',
    'https://github.com/justinhunt/moodle-atto_generico',
    'https://github.com/justinhunt/moodle-atto_poodll',
    'https://github.com/justinhunt/moodle-filter_generico',
    'https://github.com/justinhunt/moodle-filter_videoeasy',
    'https://github.com/justinhunt/moodle-mod_data_field_poodll',
    'https://github.com/justinhunt/moodle-mod_readaloud',
    'https://github.com/justinhunt/moodle-portfolio_blogexport',
    'https://github.com/justinhunt/moodle-qtype_poodllrecording',
    'https://github.com/justinhunt/moodle-tinymce_poodll',
    'https://github.com/justinhunt/moodle-tinymce_skim',
    'https://github.com/kennibc/moodle-theme_pioneer',
    'https://github.com/koenr/Moodle_openbiblo_block',
    'https://github.com/kwiliarty/moodle-filter_ipa',
    'https://github.com/lavanyamanne2/mycoursestatus',
    'https://github.com/lazydaisy/moodle-theme_aardvark_postitnote.git',
    'https://github.com/lazydaisy/moodle-theme_afterburner',
    'https://github.com/lazydaisy/moodle-theme_arialist',
    'https://github.com/lazydaisy/moodle-theme_morecandy.git',
    'https://github.com/lazydaisy/moodle-theme_serenity',
    'https://github.com/learningtechnologyservices/moodle-block_badgeawarder',
    'https://github.com/learnweb/moodle-mod_ratingallocate',
    'https://github.com/limsko/moodle-block_slider',
    'https://github.com/limsko/moodle-filter_vowels',
    'https://github.com/lmsace/academi/',
    'https://github.com/lmsace/eguru',
    'https://github.com/lmsace/klass',
    'https://github.com/lsuits/block_quickmail',
    'https://github.com/lucaboesch/moodle-quizaccess_safeexambrowser',
    'https://github.com/lucisgit/moodle-block_quickscan',
    'https://github.com/lucisgit/moodle-filter_jwplayer/',
    'https://github.com/lucisgit/moodle-qformat_qml',
    'https://github.com/m-schwabe/block_bs_recent_badges',
    'https://github.com/m-schwabe/enrol_badgeenrol',
    'https://github.com/m-schwabe/local_bs_badge_ladder',
    'https://github.com/m-schwabe/local_bs_badge_pool',
    'https://github.com/manieer/moodle-block_verify_certificate',
    'https://github.com/marcusgreen/moodle-gradingform_btec/tree/beta1',
    'https://github.com/marcusgreen/moodle-mod_qpractice',
    'https://github.com/marcusgreen/moodle-qtype_gapfill',
    'https://github.com/marinaglancy/moodle-format_flexsections',
    'https://github.com/marinaglancy/moodle-format_periods',
    'https://github.com/marxjohnson/moodle-block_accessibility',
    'https://github.com/marxjohnson/moodle-block_messageteacher',
    'https://github.com/marxjohnson/moodle-block_quickcourselist',
    'https://github.com/marxjohnson/moodle-block_quickfindlist',
    'https://github.com/matbury/mod_revealjs.git',
    'https://github.com/maths/moodle-qbehaviour_adaptivemultipart',
    'https://github.com/maths/moodle-qbehaviour_dfcbmexplicitvaildate',
    'https://github.com/maths/moodle-qbehaviour_dfexplicitvaildate',
    'https://github.com/maths/moodle-qformat_stack/',
    'https://github.com/maths/moodle-qtype_stack',
    'https://github.com/maths/quiz_stack/',
    'https://github.com/merrill-oakland/Banner-Luminis-Message-Broker-for-Moodle',
    'https://github.com/merrill-oakland/moodle-mod_webexactivity',
    'https://github.com/middlebury/moodle-mod_adaptivequiz',
    'https://github.com/moodle-saml/auth',
    'https://github.com/moodle-saml/enrol',
    'https://github.com/moodleboy/moodle-block_slideshow',
    'https://github.com/moodlehq/moodle-enrol_groupsync',
    'https://github.com/moodlehq/moodle-local_codechecker',
    'https://github.com/moodlehq/moodle-theme_anomaly',
    'https://github.com/moodlehq/moodle-theme_magazine',
    'https://github.com/moodlehq/moodle-theme_overlay',
    'https://github.com/moodlehq/moodle-theme_standard',
    'https://github.com/moodlehu/moodle-mod_etherpadlite',
    'https://github.com/moodleou/moodle-block_workflow',
    'https://github.com/moodleou/moodle-editor_supsub',
    'https://github.com/moodleou/moodle-mod_forumng',
    'https://github.com/moodleou/moodle-mod_oublog',
    'https://github.com/moodleou/moodle-mod_ouwiki',
    'https://github.com/moodleou/moodle-qbehaviour_opaque',
    'https://github.com/moodleou/moodle-qtype_combined',
    'https://github.com/moodleou/moodle-qtype_opaque',
    'https://github.com/moodleou/moodle-qtype_oumultiresponse',
    'https://github.com/moodleou/moodle-qtype_pmatch',
    'https://github.com/moodleou/moodle-qtype_pmatchjme',
    'https://github.com/moodleou/moodle-qtype_varnumeric',
    'https://github.com/moodleou/moodle-qtype_varnumericset',
    'https://github.com/moodleou/moodle-qtype_varnumunit',
    'https://github.com/moodleou/moodle-quiz_editquizsettings',
    'https://github.com/moodleou/moodle-quiz_gradingstudents',
    'https://github.com/moodleou/moodle-quizaccess_honestycheck',
    'https://github.com/moodleou/moodle-report_customsql',
    'https://github.com/moodleou/moodle-report_editdates',
    'https://github.com/moodleou/moodle-report_editgroups',
    'https://github.com/moodleou/moodle-report_editidnumber',
    'https://github.com/moodleou/moodle-report_workflow',
    'https://github.com/moodleou/moodle-tool_editrolesbycap',
    'https://github.com/moodlepeers/moodle-mod_groupformation',
    'https://github.com/moodlerooms/moodle-block_flexpagemod',
    'https://github.com/moodlerooms/moodle-block_flexpagenav',
    'https://github.com/moodlerooms/moodle-format_flexpage',
    'https://github.com/moodlerooms/moodle-gradingform_checklist',
    'https://github.com/moodlerooms/moodle-theme_flexpage',
    'https://github.com/moodleuulm/moodle-atto_styles',
    'https://github.com/moodleuulm/moodle-auth_ldap_syncplus',
    'https://github.com/moodleuulm/moodle-availability_password',
    'https://github.com/moodleuulm/moodle-availability_role',
    'https://github.com/moodleuulm/moodle-block_course_overview_campus',
    'https://github.com/moodleuulm/moodle-block_people',
    'https://github.com/moodleuulm/moodle-local_resort_courses',
    'https://github.com/moodleuulm/moodle-local_sandbox',
    'https://github.com/moodleuulm/moodle-local_staticpage',
    'https://github.com/mudrd8mz/moodle-block_course_contents',
    'https://github.com/mudrd8mz/moodle-editor_marklar',
    'https://github.com/mudrd8mz/moodle-mod_poster',
    'https://github.com/mudrd8mz/moodle-mod_stampcoll',
    'https://github.com/mudrd8mz/moodle-mod_subcourse',
    'https://github.com/mudrd8mz/moodle-report_overviewstats',
    'https://github.com/mudrd8mz/moodle-workshopeval_credit',
    'https://github.com/ndunand/moodle-atto_corrections',
    'https://github.com/ndunand/moodle-atto_morebackcolors',
    'https://github.com/ndunand/moodle-atto_morefontcolors',
    'https://github.com/ndunand/moodle-enrol_attributes',
    'https://github.com/ndunand/moodle-mod_choicegroup',
    'https://github.com/ndunand/moodle-qtype_matrix',
    'https://github.com/ndunand/moodle-qtype_multinumerical',
    'https://github.com/nebgor/moodle-repository_mediawiki',
    'https://github.com/netsapiensis/moodle-block_course_menu/tree/MOODLE_23_STABLE',
    'https://github.com/netspotau/moodle-assignsubmission_mediagallery',
    'https://github.com/netspotau/moodle-atto_mediagallery',
    'https://github.com/netspotau/moodle-block_poll',
    'https://github.com/netspotau/moodle-filter_mediagallery',
    'https://github.com/netspotau/moodle-mod_mediagallery',
    'https://github.com/netspotau/moodle-mod_teambuilder',
    'https://github.com/nitinwaves/moodle-profilefield_multiselect',
    'https://github.com/onno-schuit/copycheck',
    'https://github.com/oohoo/moodle-mod_tab',
    'https://github.com/openmeetings/openmeetings-moodle-plugin',
    'https://github.com/paulholden/moodle-local_cohortrole',
    'https://github.com/paulholden/moodle-local_metagroups',
    'https://github.com/pauln/moodle-assignsubmission_onlineaudio',
    'https://github.com/pauln/moodle-report_componentgrades',
    'https://github.com/pinoke/moodle-mod_sna',
    'https://github.com/plagiarism/moodle-plagiarism_plagiarisma',
    'https://github.com/pragodata/mojeid',
    'https://github.com/projectestac/moodle-atto_fontfamily',
    'https://github.com/projectestac/moodle-mod_geogebra',
    'https://github.com/projectestac/moodle-mod_jclic',
    'https://github.com/rabser/moodle-auth_googleoauth2',
    'https://github.com/remotelearner/moodle-block_censusreport',
    'https://github.com/remotelearner/moodle-block_grade_me',
    'https://github.com/rezaies/moodle-calendartype_hijri.git',
    'https://github.com/rezaies/moodle-calendartype_jalali.git',
    'https://github.com/rezaies/moodle-profilefield_associated.git',
    'https://github.com/rezaies/moodle-profilefield_file.git',
    'https://github.com/rezeau/moodle-block_glossary_export_to_quiz',
    'https://github.com/rezeau/moodle-block_lesson_essay_feedback',
    'https://github.com/rezeau/moodle-qbehaviour_regexpadaptivewithhelp',
    'https://github.com/rezeau/moodle-qbehaviour_regexpadaptivewithhelpnopenalty',
    'https://github.com/rezeau/moodle-qtype_regexp',
    'https://github.com/roelmann/moodle-block_course_contacts.git',
    'https://github.com/roelmann/moodle-theme_flexibase',
    'https://github.com/rogerbaba/moodle-mod_groupselect',
    'https://github.com/rogiervandongen/moodle-local_mass_enroll',
    'https://github.com/sbourget/moodle-mod_pcast',
    'https://github.com/silecs/moodle-local-resourcenotif',
    'https://github.com/simoncoggins/moodle-tool_capexplorer',
    'https://github.com/streamingltd',
    'https://github.com/superawesomeme/moodle-theme_aardvark',
    'https://github.com/synergylearning/moodle-local_wikiexport',
    'https://github.com/synergylearning/moodle-mod_giportfolio',
    'https://github.com/synergylearning/moodle-mod_klassenbuch',
    'https://github.com/synergylearning/moodle-mod_vitero',
    'https://github.com/t6nis/moodle-block_forum_aggregator',
    'https://github.com/t6nis/moodle-mod_mindmap',
    'https://github.com/telabotanica/moodle-block_completeyourprofile',
    'https://github.com/tim1mw/autoview-moodle-activity',
    'https://github.com/tim1mw/coursefilearea-moodle-repo',
    'https://github.com/tim1mw/repo_filemanager-moodle-block',
    'https://github.com/timhunt/moodle-qbehaviour_deferredfeedbackexplain',
    'https://github.com/timhunt/moodle-qtype_pmatchreverse',
    'https://github.com/timhunt/moodle-quizaccess_offlinemode',
    'https://github.com/tonyjbutler/moodle-mod_aspirelist',
    'https://github.com/tonyjbutler/moodle-mod_nln',
    'https://github.com/tonyjbutler/moodle-tinymce_wordcount',
    'https://github.com/troywilliams/moodle-mod_dialogue',
    'https://github.com/tunele/moodle-profilefield_dynamicmenu',
    'https://github.com/turnitin/moodle-block_turnitin',
    'https://github.com/turnitin/moodle-mod_turnitintool',
    'https://github.com/turnitin/moodle-mod_turnitintooltwo',
    'https://github.com/ualberta-eclass/moodle-block_demostudent',
    'https://github.com/ucla/moodle-mod_zoom',
    'https://github.com/uclmoodle/moodle-enrol_dbuserrel',
    'https://github.com/uclmoodle/moodle-report_myfeedback',
    'https://github.com/unikent/moodle-tool_adhoc/',
    'https://github.com/vadimonus/moodle-block_graph_stats',
    'https://github.com/vadimonus/moodle-block_iprbookshop_ru',
    'https://github.com/vadimonus/moodle-block_znanium_com',
    'https://github.com/vadimonus/moodle-filter_iprbookshop_ru',
    'https://github.com/vanyog/moodle-filter_multilangsecond',
    'https://github.com/vericite/moodle-plagiarism_vericite',
    'https://github.com/vfremaux/moodle-block_profilespecifichtml',
    'https://github.com/vfremaux/moodle-block_rolespecifichtml',
    'https://github.com/vfremaux/moodle-mod_customlabel',
    'https://github.com/vfremaux/moodle-mod_flashcard',
    'https://github.com/vfremaux/moodle-mod_magtest',
    'https://github.com/vfremaux/moodle-mod_mplayer.git',
    'https://github.com/vfremaux/moodle-qtype_splitset',
    'https://github.com/vfremaux/moodle-tool_sync',
    'https://github.com/vidyamantra/moodle-local_getkey',
    'https://github.com/vidyamantra/moodle-local_vmchat',
    'https://github.com/vidyamantra/moodle-mod_exam',
    'https://github.com/vidyamantra/moodle-theme_eduhub',
    'https://github.com/willianmano/moodle-block_ranking',
    'https://github.com/willianmano/moodle-profilefield_cpf',
    'https://github.com/wiris/moodle-atto_wiris.git',
    'https://github.com/wiris/moodle-filter_wiris',
    'https://github.com/wiris/moodle-tinymce_tiny_mce_wiris.git',
    'https://github.com/wjunkin/moodle-mod_ipal/tree/MOODLE_3.3_STABLE',
    'https://gitlab.com/albertgasset/moodle-repository_s3links',
    'https://gitlab.com/albertgasset/moodle-workshopallocation_live',
    'https://gitlab.com/albertgasset/moodle-workshopeval_weightiest',
    'https://gitlab.com/api/v4/projects/jezhops%2Fmoodle-theme_adaptable%2Ftree%2Fmaster',
    'https://gitlab.com/drlikm/format_etask',
    'https://gitlab.com/reskity/moodle-local_mail',
    'https://moodle.org/plugins/format_mindmap',
];

foreach ($pluginlist->plugins as $key => $plugin) {
    if (empty($plugin->component) || empty($plugin->source)) {
        continue;
    }
    // Check if source (vcs repository) have a valid URL
    if (filter_var($plugin->source, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED) === false) {
        continue;
    }
    // Check if source (vcs repository) is HTTPS
    $url = parse_url($plugin->source);
    if (!isset($url['path']) || strpos($plugin->source, 'http:') !== false) {
        continue;
    }
    // Plugins without composer.json that we knows
    if (in_array($plugin->source, $ignore)) {
        continue;
    }
    // Support to Moodle 3.2+
    $suport = false;
    foreach ($plugin->versions as $version) {
        foreach ($version->supportedmoodles as $supportedmoodle) {
            if ($suport || $supportedmoodle->version >= 2015110100) {
                $suport = true;
            }
        }
    }
    if (!$suport) {
        continue;
    }
    // All right
    $satisjson['repositories'][] = ["type" => "vcs", "url" => $plugin->source];
}

$plugins = [
	['source' => 'https://github.com/michaelmeneses/moodle-atto_styles'],
	['source' => 'https://github.com/michaelmeneses/moodle-atto_morefontcolors'],
	['source' => 'https://github.com/michaelmeneses/moodle-block_completion_progress'],
	['source' => 'https://github.com/michaelmeneses/moodle-filter_wiris'],
	['source' => 'https://github.com/michaelmeneses/moodle-atto_wiris'],
	['source' => 'https://github.com/michaelmeneses/moodle-tinymce_tiny_mce_wiris'],
	['source' => 'https://github.com/michaelmeneses/moodle-format_topcoll'],
	['source' => 'https://github.com/michaelmeneses/moodle-local_mailtest'],
	['source' => 'https://github.com/michaelmeneses/moodle-local_welcome'],
	['source' => 'https://github.com/michaelmeneses/h5p-moodle-plugin'],
	['source' => 'https://github.com/michaelmeneses/moodle-atto_htmlplus'],
	['source' => 'https://github.com/michaelmeneses/moodle-objectives'],
	['source' => 'https://github.com/michaelmeneses/moodle-mod_congrea'],
	['source' => 'https://github.com/michaelmeneses/moodle-theme_moove'],
	['source' => 'https://github.com/michaelmeneses/moodle-theme_snap'],
	['source' => 'https://github.com/michaelmeneses/moodle-format_remuiformat'],
	['source' => 'https://github.com/michaelmeneses/moodle-block_grade_me'],
];

foreach ($plugins as $plugin) {
    $satisjson['repositories'][] = ["type" => "vcs", "url" => $plugin['source']];
}

$satisjson['require-all'] = true;
$satisjson['require-dependencies'] = true;
$satisjson['require-dev-dependencies'] = true;
$satisjson['output-dir'] = "public_html";
$satisjson['archive'] = ["directory" => "dist", "format" => "tar"];

file_put_contents($satisfile, json_encode($satisjson));
