<?php

$api = "https://download.moodle.org/api/1.3/pluglist.php";
$satisfile = __DIR__ . '/satis.json';

$pluginlistjson = file_get_contents($api);

if (!$pluginlist = json_decode($pluginlistjson)) {
    die("Unable to read plugin list");
}

$satisjson = [];
$satisjson['name'] = "michaelmeneses/moodle-plugin-repo";
$satisjson['homepage'] = "https://satis.middag.com.br";
$satisjson['repositories'] = [];

$ignore = [
    'https://github.com/superawesomeme/moodle-theme_aardvark',
    'https://github.com/deraadt/moodle-block_simple_clock.git',
    'https://github.com/deraadt/moodle-block_unanswered_discussions',
    'https://github.com/deraadt/moodle-block_progress',
    'https://github.com/mudrd8mz/moodle-mod_stampcoll',
    'https://github.com/davosmith/moodle-navbuttons',
    'https://github.com/davosmith/moodle-realtimequiz',
    'https://github.com/davosmith/moodle-objectives',
    'https://github.com/CTANZ/moodle-theme_decaf',
    'https://github.com/itamart/moodle-mod_dataform',
    'https://github.com/moodlehq/moodle-local_codechecker',
    'https://github.com/RusticiSoftware/SCORMCloud_MoodleModule',
    'https://github.com/troywilliams/moodle-mod_dialogue',
    'https://github.com/rabser/moodle-auth_googleoauth2',
    'https://github.com/SonicFoundry/Mediasite-Content-Module-for-Moodle',
    'https://github.com/moodleou/moodle-mod_forumng',
    'https://github.com/moodleou/moodle-mod_oublog',
    'https://github.com/moodleou/moodle-mod_ouwiki',
    'https://github.com/rezeau/moodle-block_glossary_export_to_quiz',
    'https://github.com/lsuits/block_quickmail',
    'https://github.com/blindsidenetworks/moodle-mod_recordingsbn',
    'https://github.com/tim1mw/coursefilearea-moodle-repo',
    'https://github.com/tim1mw/repo_filemanager-moodle-block',
    'https://github.com/tim1mw/autoview-moodle-activity',
    'https://github.com/rezeau/moodle-block_lesson_essay_feedback',
    'https://github.com/itamart/moodle-block_dataform_view',
    'https://github.com/gjb2048/moodle-format_topcoll.git',
    'https://github.com/openmeetings/openmeetings-moodle-plugin',
    'https://github.com/sbourget/moodle-mod_pcast',
    'https://github.com/at-tools/moodle-block_massaction',
    'https://github.com/moodle-saml/auth',
    'https://github.com/moodle-saml/enrol',
    'https://github.com/rogerbaba/moodle-mod_groupselect',
    'https://github.com/elearningsoftware/moodle-mod_journal',
    'https://github.com/drachels/moodle-mod_hotquestion',
    'https://github.com/rezeau/moodle-qbehaviour_regexpadaptivewithhelp',
    'https://github.com/rezeau/moodle-qbehaviour_regexpadaptivewithhelpnopenalty',
    'https://github.com/rezeau/moodle-qtype_regexp',
    'https://github.com/bostelm/moodle-mod_scheduler',
    'https://github.com/mudrd8mz/moodle-block_course_contents',
    'https://github.com/vfremaux/moodle-mod_flashcard',
    'https://github.com/ndunand/moodle-qtype_multinumerical',
    'https://github.com/ndunand/moodle-mod_choicegroup',
    'https://github.com/bobopinna/moodle-mod_reservation',
    'https://github.com/oohoo/moodle-mod_tab',
    'https://github.com/gtn/exaport',
    'https://github.com/grabs/moodle-local_adminer.git',
    'https://github.com/projectestac/moodle-mod_geogebra',
    'https://github.com/aduranterres/enrol_signup',
    'https://github.com/davosmith/moodle-checklist',
    'https://github.com/davosmith/moodle-block_checklist',
    'https://github.com/davosmith/moodle-grade_checklist',
    'https://github.com/adrienedunao/mod_richmedia',
    'https://github.com/academic-moodle-cooperation/moodle-mod_checkmark',
    'https://github.com/catalyst/moodle-mod_facetoface/',
    'https://github.com/danmarsden/moodle-plagiarism_urkund',
    'https://github.com/moodleou/moodle-report_customsql',
    'https://github.com/marxjohnson/moodle-block_quickfindlist',
    'https://github.com/marxjohnson/moodle-block_messageteacher',
    'https://github.com/marxjohnson/moodle-block_quickcourselist',
    'https://github.com/ed-rom/moodle-auth_uniquelogin',
    'https://github.com/aduranterres/auth_joomdle',
    'https://github.com/marxjohnson/moodle-block_accessibility',
    'https://github.com/vadimonus/moodle-block_graph_stats',
    'https://github.com/wiris/moodle-filter_wiris',
    'https://github.com/jleyva/moodle-local_anonymousposting',
    'https://github.com/roelmann/moodle-block_course_contacts.git',
    'https://github.com/dualcube/moodle-theme_rocket',
    'https://github.com/coderader/moodle-block_userexpire',
    'https://github.com/benchen71/moodle-filter_toc',
    'https://github.com/moodleou/moodle-editor_supsub',
    'https://github.com/moodleou/moodle-qtype_pmatchjme',
    'https://github.com/moodleou/moodle-qtype_pmatch',
    'https://github.com/moodleou/moodle-qtype_oumultiresponse',
    'https://github.com/moodleou/moodle-qtype_varnumericset',
    'https://github.com/moodleou/moodle-qtype_varnumeric',
    'https://github.com/moodleou/moodle-qtype_opaque',
    'https://github.com/moodleou/moodle-qbehaviour_opaque',
    'https://github.com/CinecaElearning/moodle-mod_attendanceregister',
    'https://github.com/arborrow/moodle-block_mrbs',
    'https://github.com/turnitin/moodle-mod_turnitintool',
    'https://github.com/ndunand/moodle-qtype_matrix',
    'https://github.com/drachels/moodle-mod_skype',
    'https://github.com/DigiDago/moodle-block_admin_presets',
    'https://github.com/tonyjbutler/moodle-mod_nln',
    'https://github.com/merrill-oakland/Banner-Luminis-Message-Broker-for-Moodle',
    'https://github.com/dasistwas/moodle-mod_booking/',
    'https://github.com/curupira/moodle-mod_registration',
    'https://github.com/ak4t0sh/moodle-format_weeksrev',
    'https://github.com/gtn/exagames',
    'https://github.com/projectestac/moodle-mod_jclic',
    'https://github.com/justinhunt/moodle-qtype_poodllrecording',
    'https://github.com/koenr/Moodle_openbiblo_block',
    'https://github.com/moodleou/moodle-report_editidnumber',
    'https://github.com/moodleou/moodle-report_editdates',
    'https://github.com/moodleou/moodle-report_editgroups',
    'https://github.com/moodleou/moodle-tool_editrolesbycap',
    'https://github.com/t6nis/moodle-block_forum_aggregator',
    'https://github.com/moodleuulm/moodle-local_resort_courses',
    'https://github.com/moodleuulm/moodle-local_staticpage',
    'https://github.com/moodleuulm/moodle-block_people',
    'https://github.com/t6nis/moodle-mod_mindmap',
    'https://github.com/bobopinna/moodle-enrol_autoenrol',
    'https://github.com/appalachianstate/moodle-enrol_shebang',
    'https://github.com/andil-elearning/moodle-block_section',
    'https://github.com/dasistwas/moodle-block_simple_nav/',
    'https://github.com/moodlerooms/moodle-block_flexpagemod',
    'https://github.com/moodlerooms/moodle-block_flexpagenav',
    'https://github.com/moodlerooms/moodle-format_flexpage',
    'https://github.com/moodlerooms/moodle-theme_flexpage',
    'https://github.com/drachels/moodle-mod_mootyper',
    'https://github.com/maths/moodle-qbehaviour_adaptivemultipart',
    'https://github.com/maths/moodle-qbehaviour_dfexplicitvaildate',
    'https://github.com/maths/moodle-qbehaviour_dfcbmexplicitvaildate',
    'https://github.com/maths/moodle-qtype_stack',
    'https://github.com/maths/moodle-qformat_stack/',
    'https://github.com/blackboard-open-source/moodle-format_folderview',
    'https://github.com/moodlerooms/moodle-gradingform_checklist',
    'https://github.com/Kylegoslin/Course-Request-Manager',
    'https://github.com/isuru89/moodle-reminders-for-calendar-events',
    'https://github.com/blackboard-open-source/moodle-mod_hsuforum',
    'https://api.github.com/repos/compilatio/moodle-plagiarism_compilatio/tree/PLUGIN_24_STABLE"',
    'https://github.com/jleyva/moodle-block_jmail',
    'https://api.github.com/repos/netsapiensis/moodle-block_course_menu/tree/MOODLE_23_STABLE"',
    'https://github.com/ankitagarwal/advanced_spam_cleaner',
    'https://github.com/moodleou/moodle-block_workflow',
    'https://github.com/moodleou/moodle-report_workflow',
    'https://github.com/itamart/moodle-local_loginas',
    'https://github.com/pauln/moodle-assignsubmission_onlineaudio',
    'https://github.com/bmbrands/moodle-local_welcome',
    'https://github.com/itamart/moodle-mod_dataformembed',
    'https://github.com/remotelearner/moodle-block_censusreport',
    'https://github.com/lazydaisy/moodle-theme_aardvark_postitnote.git',
    'https://github.com/EizEddin/moodle-block_login_userinfo',
    'https://api.github.com/repos/FMCorz/moodle-repository_evernote/tree/plugin"',
    'https://github.com/fschuett/moodle-enrol_openlml',
    'https://github.com/rogiervandongen/moodle-local_mass_enroll',
    'https://github.com/vfremaux/moodle-block_profilespecifichtml',
    'https://github.com/vfremaux/moodle-block_rolespecifichtml',
    'https://github.com/gbateson/moodle-mod_taskchain',
    'https://github.com/justinhunt/moodle-mod_data_field_poodll',
    'https://github.com/uclmoodle/moodle-enrol_dbuserrel',
    'https://github.com/marcusgreen/moodle-qtype_gapfill',
    'https://github.com/johndimopoulos/moodle-gradingform_erubric',
    'https://github.com/vfremaux/moodle-mod_magtest',
    'https://github.com/h-honda/moodle-block_login_info',
    'https://github.com/ecampbell/moodle-qformat_wordtable',
    'https://github.com/marinaglancy/moodle-format_flexsections',
    'https://github.com/josePFs/moodle-filter_tabs',
    'https://github.com/UNEDLabs/moodle-mod_ejsapp',
    'https://github.com/UNEDLabs/moodle-mod_ejsappbooking',
    'https://github.com/UNEDLabs/moodle-block_ejsapp_file_browser',
    'https://github.com/UNEDLabs/moodle-block_ejsapp_collab_session',
    'https://github.com/hrimhari/moodle-auth_emailadmin',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://github.com/donhinkelman/moodle-block_sharing_cart',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://github.com/vfremaux/moodle-mod_customlabel',
    'https://github.com/moodleuulm/moodle-block_course_overview_campus',
    'https://github.com/moodlehq/moodle-enrol_groupsync',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://github.com/vfremaux/moodle-qtype_splitset',
    'https://github.com/davosmith/moodle-assignsubmission_pdf',
    'https://github.com/davosmith/moodle-assignfeedback_pdf',
    'https://github.com/gjb2048/moodle-block_theme_selector.git',
    'https://github.com/actXc/moodle_filter_botr',
    'https://github.com/ewallah/moodle-format_masonry',
    'https://github.com/emeneo/moodle-enrol_waitlist',
    'https://github.com/moodleuulm/moodle-local_sandbox',
    'https://github.com/EllucianMoodleIntegration/moodle-block_intelligent_learning',
    'https://github.com/blackboard-open-source/moodle-local_mr',
    'https://github.com/vfremaux/moodle-mod_mplayer.git',
    'https://github.com/netspotau/moodle-block_poll',
    'https://github.com/moodleou/moodle-quizaccess_honestycheck',
    'https://gitlab.com/reskity/moodle-local_mail',
    'https://github.com/iandavidwild/moodle-mod_enhancedchoice',
    'https://api.github.com/repos/arael/moodle_notifications_20"',
    'https://github.com/mudrd8mz/moodle-workshopeval_credit',
    'https://github.com/synergylearning/moodle-mod_vitero',
    'https://github.com/justinhunt/moodle-portfolio_blogexport',
    'https://github.com/dasistwas/moodle-block_simple_map',
    'https://github.com/UbiCastTeam/moodle-mod_easycastms.git',
    'https://github.com/iautomatebr/moodle-block_moodleversion',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://github.com/moodleou/moodle-qtype_varnumunit',
    'https://github.com/eberhardt/moodle-block_coursefeedback',
    'https://github.com/appalachianstate/moodle-local_userenrols',
    'https://github.com/eledia/eledia_cohortgreeting.git',
    'https://github.com/jmvedrine/moodle-qformat_giftmedia',
    'https://github.com/ankitagarwal/moodle-block_fbcomments.git',
    'https://github.com/timhunt/moodle-qtype_pmatchreverse',
    'https://gitlab.com/drlikm/format_etask',
    'https://github.com/gjb2048/moodle-theme_shoelace',
    'https://github.com/justinhunt/moodle-assignfeedback_poodll.git',
    'https://github.com/lucaboesch/moodle-quizaccess_safeexambrowser',
    'https://github.com/dualcube/Drag-and-Drop-Matching',
    'https://github.com/jmvedrine/moodle-qtype_algebra',
    'https://github.com/justinhunt/moodle-assign_submission_onlinepoodll',
    'https://github.com/ankitagarwal/moodle-scormreport_trends',
    'https://github.com/ndunand/moodle-enrol_attributes',
    'https://github.com/middlebury/moodle-mod_adaptivequiz',
    'https://github.com/Kylegoslin/moodle-block_faces',
    'https://github.com/justinhunt/moodle-tinymce_skim',
    'https://github.com/LafColITS/moodle-report_roster',
    'https://github.com/daveyboond/moodle-mcq-report-only',
    'https://github.com/moodleou/moodle-qtype_combined',
    'https://github.com/maths/quiz_stack/',
    'https://api.github.com/repositories/12539788/tree/master?access_token=eb0f904557aa3f131c98c133e8991961cb6e1380"',
    'https://github.com/MaharaProject/moodle-assignsubmission_mahara',
    'https://github.com/3ilogiclms/moodle-theme_sharp',
    'https://github.com/3ilogiclms/moodle-theme_contemporary',
    'https://github.com/3ilogiclms/moodle-theme_dynamic',
    'https://github.com/humanage/moodle-mod_eduplayer',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://github.com/3ilogiclms/moodle-block_profile_field_identifier',
    'https://github.com/3ilogiclms/moodle-block_course_status_tracker',
    'https://github.com/3ilogiclms/moodle-block_course_finder',
    'https://github.com/3ilogiclms/moodle-block_sms',
    'https://github.com/SVIeSolutions/moodle-mod_via',
    'https://github.com/garemoko/moodle-mod_tincanlaunch',
    'https://github.com/francpombal/moodle-theme_aigne/',
    'https://github.com/marcusgreen/moodle-mod_qpractice',
    'https://github.com/moodleboy/moodle-block_slideshow',
    'https://api.github.com/repos/ctchanandy/moodle-report_forumgraph/tree/Moodle-3.1"',
    'https://github.com/ensembleVideo/moodle-repository_ensemble/',
    'https://github.com/jmpease/moodle-filter_ensemble/',
    'https://github.com/abgreeve/moodle-calendartype_japanese',
    'https://github.com/Kylegoslin/moodle-block_signinsheet',
    'https://api.github.com/repositories/12540260/tree/master?access_token=eb0f904557aa3f131c98c133e8991961cb6e1380"',
    'https://github.com/mudrd8mz/moodle-report_overviewstats',
    'https://github.com/nebgor/moodle-repository_mediawiki',
    'https://github.com/3ilogiclms/moodle-block_learning_plan',
    'https://api.github.com/repos/eledia/block_eledia_userdelete/tree/v_34/blocks/eledia_userdelete"',
    'https://github.com/synergylearning/moodle-mod_klassenbuch',
    'https://github.com/synergylearning/moodle-mod_giportfolio',
    'https://github.com/matbury/mod_revealjs.git',
    'https://github.com/eledia/block_eledia_suspenduser.git',
    'https://api.github.com/repos/eledia/eledia_course_archiving/tree/v_25/blocks/eledia_course_archiving"',
    'https://github.com/ffhs/moodle-filter_fontawesome',
    'https://github.com/vanyog/moodle-filter_multilangsecond',
    'https://github.com/SREd-URV/moodle-auth_ip',
    'https://github.com/SREd-URV/moodle-profilefield_timestamp',
    'https://github.com/gbateson/moodle-mod_reader',
    'https://github.com/rezaies/moodle-calendartype_jalali.git',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://bitbucket.org/oasychev/moodle-plugins',
    'https://github.com/remotelearner/moodle-block_grade_me',
    'https://github.com/eledia/block_eledia_trainerinfo',
    'https://github.com/mudrd8mz/moodle-mod_subcourse',
    'https://github.com/paulholden/moodle-local_cohortrole',
    'https://github.com/ualberta-eclass/moodle-block_demostudent',
    'https://github.com/ualberta-eclass/moodle-block_demostudent',
    'https://github.com/UNEDLabs/moodle-repository_osp',
    'https://github.com/rezaies/moodle-calendartype_hijri.git',
    'https://github.com/justinhunt/moodle-tinymce_poodll',
    'https://github.com/ak4t0sh/moodle-filter_codepen',
    'https://github.com/moodleou/moodle-quiz_gradingstudents',
    'https://github.com/moodleou/moodle-quiz_editquizsettings',
    'https://github.com/ecampbell/moodle-qformat_htmltable',
    'https://github.com/dasistwas/moodle-mod_newsletter',
    'https://github.com/gbateson/moodle-qtype_ordering',
    'https://github.com/paulholden/moodle-local_metagroups',
    'https://github.com/willianmano/moodle-block_ranking',
    'https://github.com/dthies/moodle-editor_tinymce-mathslate',
    'https://github.com/merrill-oakland/moodle-mod_webexactivity',
    'https://github.com/andiglombitza/CLOZE_editor_Moodle2.2',
    'https://github.com/turnitin/moodle-mod_turnitintooltwo',
    'https://github.com/turnitin/moodle-block_turnitin',
    'https://github.com/moodleuulm/moodle-auth_ldap_syncplus',
];

foreach ($pluginlist->plugins as $key => $plugin) {
    if (empty($plugin->component) || empty($plugin->source)) {
        continue;
    }
    // Check if source (vcs repository) have a valid URL
    if (filter_var($plugin->source, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED) === false) {
        continue;
    }
    // Check if source (vcs repository) is HTTPS
    $url = parse_url($plugin->source);
    if (!isset($url['path']) || strpos($plugin->source, 'http:') !== false) {
        continue;
    }
    // Plugins without composer.json that we knows
    if (in_array($plugin->source, $ignore)) {
        continue;
    }
    // Support to Moodle 3.2+
    $suport = false;
    foreach ($plugin->versions as $version) {
        foreach ($version->supportedmoodles as $supportedmoodle) {
            if ($suport || $supportedmoodle->version >= 2015110100) {
                $suport = true;
            }
        }
    }
    if (!$suport) {
        continue;
    }
    // All right
    $satisjson['repositories'][] = ["type" => "vcs", "url" => $plugin->source];
}

$plugins = [
	['source' => 'https://github.com/michaelmeneses/moodle-atto_styles'],
	['source' => 'https://github.com/michaelmeneses/moodle-atto_morefontcolors'],
	['source' => 'https://github.com/michaelmeneses/moodle-block_completion_progress'],
	['source' => 'https://github.com/michaelmeneses/moodle-filter_wiris'],
	['source' => 'https://github.com/michaelmeneses/moodle-atto_wiris'],
	['source' => 'https://github.com/michaelmeneses/moodle-tinymce_tiny_mce_wiris'],
	['source' => 'https://github.com/michaelmeneses/moodle-format_topcoll'],
	['source' => 'https://github.com/michaelmeneses/moodle-local_mailtest'],
	['source' => 'https://github.com/michaelmeneses/moodle-local_welcome'],
	['source' => 'https://github.com/michaelmeneses/h5p-moodle-plugin'],
	['source' => 'https://github.com/michaelmeneses/moodle-atto_htmlplus'],
	['source' => 'https://github.com/michaelmeneses/moodle-objectives'],
	['source' => 'https://github.com/michaelmeneses/moodle-mod_congrea'],
	['source' => 'https://github.com/michaelmeneses/moodle-theme_moove'],
	['source' => 'https://github.com/michaelmeneses/moodle-theme_snap'],
	['source' => 'https://github.com/michaelmeneses/moodle-format_remuiformat'],
	['source' => 'https://github.com/michaelmeneses/moodle-block_grade_me'],
];

foreach ($plugins as $plugin) {
    $satisjson['repositories'][] = ["type" => "vcs", "url" => $plugin['source']];
}

$satisjson['require-all'] = true;
$satisjson['require-dependencies'] = true;
$satisjson['require-dev-dependencies'] = true;
$satisjson['output-dir'] = "public_html";
$satisjson['archive'] = ["directory" => "dist", "format" => "tar"];

file_put_contents($satisfile, json_encode($satisjson));
