name: Build Satis

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Satis
    runs-on: ubuntu-latest

    container:
      image: composer:latest

    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_PROCESS_TIMEOUT: 900

      # Envs variables for Satis MIDDAG
      SATIS_NAME: ${{ vars.SATIS_NAME }}
      SATIS_URL: ${{ vars.SATIS_URL }}

      # Envs variables for S3 Satis
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      S3_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_REGION: ${{ vars.S3_REGION }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      S3_USE_PATH_STYLE_ENDPOINT: ${{ vars.S3_USE_PATH_STYLE_ENDPOINT }}

    steps:
      - name: Install system dependencies
        run: apt-get update && apt-get install -y git

      - name: Checkout source-code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Build s3-satis
        run: |
          set -e
          echo "Running composer run full:s3-satis"
          composer run full:s3-satis
