name: Build Satis with Fix Checksums

on:
  workflow_dispatch:

jobs:
  build-fix:
    name: Build with --fix-checksums and Deploy Satis
    runs-on: ubuntu-latest

    container:
      image: middagtec/image-bitbucket-ci:v5-php82
      options: --user root

    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      PROCESS_TIMEOUT: 1800
      COMPOSER_PROCESS_TIMEOUT: 1800
      COMPOSER_MEMORY_LIMIT: -1

      # Envs for Satis MIDDAG
      SATIS_NAME: ${{ vars.SATIS_NAME }}
      SATIS_URL: ${{ vars.SATIS_URL }}

      # Envs for S3 Satis (Cloudflare R2)
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      S3_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_REGION: ${{ vars.S3_REGION }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      S3_USE_PATH_STYLE_ENDPOINT: ${{ vars.S3_USE_PATH_STYLE_ENDPOINT }}

    steps:
      - name: Checkout source-code
        uses: actions/checkout@v4

      - name: Restore Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Restore VCS mirrors cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer/vcs
          key: satis-vcs-${{ runner.os }}
          restore-keys: |
            satis-vcs-${{ runner.os }}

      - name: Restore S3-Satis cache
        uses: actions/cache@v4
        with:
          path: /tmp/s3-satis-generator
          key: s3-satis-${{ runner.os }}
          restore-keys: |
            s3-satis-${{ runner.os }}

      - name: Build s3-satis with --fix-checksums
        run: |
          set -e
          echo "Running composer run full:s3-satis:fix-checksums"
          composer run full:s3-satis:fix-checksums

      - name: Show cache state summary
        run: |
          echo "Cache states:"
          du -sh ~/.composer/cache || true
          du -sh ~/.cache/composer/vcs || true
          du -sh /tmp/s3-satis-generator || true
