name: Build Satis

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Satis
    runs-on: ubuntu-latest

    container:
      image: middagtec/image-bitbucket-ci:v5-php82
      options: --user root

    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      PROCESS_TIMEOUT: 21600
      COMPOSER_PROCESS_TIMEOUT: 21600
      COMPOSER_MEMORY_LIMIT: -1

      # Envs for Satis MIDDAG
      SATIS_NAME: ${{ vars.SATIS_NAME }}
      SATIS_URL: ${{ vars.SATIS_URL }}

      # Envs for S3 Satis (Cloudflare R2)
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      S3_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_REGION: ${{ vars.S3_REGION }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      S3_USE_PATH_STYLE_ENDPOINT: ${{ vars.S3_USE_PATH_STYLE_ENDPOINT }}

    steps:
      - name: Checkout source-code
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Restore temp checksums cache
        id: restore-temp-checksums
        uses: actions/cache/restore@v4
        with:
          path: /tmp/s3-generate-checksums
          key: checksums-temp-${{ runner.os }}
          restore-keys: |
            checksums-temp-${{ runner.os }}

      - name: Restore S3-Satis cache
        id: restore-s3-satis
        uses: actions/cache/restore@v4
        with:
          path: /tmp/s3-satis-generator
          key: s3-satis-${{ runner.os }}
          restore-keys: |
            s3-satis-${{ runner.os }}

      - name: Install AWS CLI if needed
        run: |
          set -e
          if ! command -v aws &> /dev/null; then
            echo ">> AWS CLI not found. Installing AWS CLI v2..."
            cd /tmp
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            ./aws/install
            rm -rf awscliv2.zip aws
          else
            echo ">> AWS CLI already installed"
          fi
          aws --version

      - name: Fix checksums before build
        run: |
          set -e
          echo ">> Running s3-generate-checksums.sh to verify and fix any missing checksums"
          chmod +x scripts/s3-generate-checksums.sh
          TMP_WORK=/tmp/s3-generate-checksums composer run checksums:s3

      - name: Sync local checksums caches
        run: |
          set -e
          echo ">> Syncing local .checksums caches with rsync between /tmp/s3-generate-checksums and /tmp/s3-satis-generator (prefer /tmp/s3-generate-checksums/checksums)"
          # Ensure both directories exist
          mkdir -p /tmp/s3-generate-checksums/checksums
          mkdir -p /tmp/s3-satis-generator/.checksums
          # 1) Push from preferred → secondary: overwrite differing files, do NOT delete extras on destination
          rsync -a /tmp/s3-generate-checksums/checksums/ /tmp/s3-satis-generator/.checksums/
          # 2) Backfill from secondary → preferred: only copy files that don't exist on destination (no overwrite)
          rsync -a --ignore-existing /tmp/s3-satis-generator/.checksums/ /tmp/s3-generate-checksums/checksums/
          echo ">> Done syncing local .checksums caches with rsync"

      - name: Build s3-satis
        run: |
          set -e
          echo "Running composer run full:s3-satis"
          composer run full:s3-satis

      - name: Save temp checksums cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: /tmp/s3-generate-checksums
          key: checksums-temp-${{ runner.os }}

      - name: Save S3-Satis cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: /tmp/s3-satis-generator
          key: s3-satis-${{ runner.os }}

      - name: Show cache state summary
        run: |
          echo "Cache states:"
          du -sh /root/.cache/composer || true
          du -sh /tmp/s3-satis-generator || true
          du -sh /tmp/s3-generate-checksums || true

  modify_html:
    name: Modify index.html with custom CSS
    needs: build
    uses: ./.github/workflows/modify-html.yml
    secrets: inherit
