name: Fix Checksums

on:
  workflow_dispatch:

jobs:
  fix-checksums:
    name: Fix Checksums
    runs-on: ubuntu-latest

    container:
      image: middagtec/image-bitbucket-ci:v5-php82
      options: --user root

    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      PROCESS_TIMEOUT: 21600
      COMPOSER_PROCESS_TIMEOUT: 21600
      COMPOSER_MEMORY_LIMIT: -1

      # Envs for Satis MIDDAG
      SATIS_NAME: ${{ vars.SATIS_NAME }}
      SATIS_URL: ${{ vars.SATIS_URL }}

      # Envs for S3 Satis (Cloudflare R2)
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      S3_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_REGION: ${{ vars.S3_REGION }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      S3_USE_PATH_STYLE_ENDPOINT: ${{ vars.S3_USE_PATH_STYLE_ENDPOINT }}

    steps:
      - name: Checkout source-code
        uses: actions/checkout@v4

      - name: Restore temp checksums cache
        uses: actions/cache@v4
        with:
          path: ./temp
          key: checksums-temp-${{ runner.os }}
          restore-keys: |
            checksums-temp-${{ runner.os }}

      - name: Install AWS CLI if needed
        run: |
          set -e
          if ! command -v aws &> /dev/null; then
            echo ">> AWS CLI not found. Installing AWS CLI v2..."
            cd /tmp
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            ./aws/install
            rm -rf awscliv2.zip aws
          else
            echo ">> AWS CLI already installed"
          fi
          aws --version

      - name: Generate missing checksums with script
        run: |
          set -e
          echo ">> Running s3-generate-checksums.sh to verify and fix any missing checksums"
          chmod +x scripts/s3-generate-checksums.sh
          composer run checksums:s3

      - name: Show cache state summary
        run: |
          echo "Cache states:"
          du -sh ./temp || true
